USE [master]
GO
/****** Object:  Database [FantasyFootballDB]    Script Date: 4/9/2020 9:49:32 AM ******/
CREATE DATABASE [FantasyFootballDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FantasyFootballDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\FantasyFootballDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FantasyFootballDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\FantasyFootballDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [FantasyFootballDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FantasyFootballDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FantasyFootballDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FantasyFootballDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FantasyFootballDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FantasyFootballDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FantasyFootballDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [FantasyFootballDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FantasyFootballDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FantasyFootballDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FantasyFootballDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FantasyFootballDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FantasyFootballDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FantasyFootballDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FantasyFootballDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FantasyFootballDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FantasyFootballDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [FantasyFootballDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FantasyFootballDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FantasyFootballDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FantasyFootballDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FantasyFootballDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FantasyFootballDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FantasyFootballDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FantasyFootballDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [FantasyFootballDB] SET  MULTI_USER 
GO
ALTER DATABASE [FantasyFootballDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FantasyFootballDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FantasyFootballDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FantasyFootballDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FantasyFootballDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FantasyFootballDB] SET QUERY_STORE = OFF
GO
USE [FantasyFootballDB]
GO
/****** Object:  Table [dbo].[NewRoster]    Script Date: 4/9/2020 9:49:32 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NewRoster](
	[PlayerID] [int] IDENTITY(1,1) NOT NULL,
	[RosterID] [int] NOT NULL,
	[PlayerName] [nvarchar](50) NOT NULL,
	[PlayerSalary] [int] NOT NULL,
 CONSTRAINT [PK_NewRoster] PRIMARY KEY CLUSTERED 
(
	[PlayerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PossibleRosters]    Script Date: 4/9/2020 9:49:32 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PossibleRosters](
	[PossibleRosterID] [int] IDENTITY(1,1) NOT NULL,
	[PlayerID] [int] NOT NULL,
	[Rosters] [nvarchar](15) NOT NULL,
	[SavedRosterID] [int] NOT NULL,
 CONSTRAINT [PK_PossibleRosters] PRIMARY KEY CLUSTERED 
(
	[PossibleRosterID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SavedRosters]    Script Date: 4/9/2020 9:49:32 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SavedRosters](
	[rosterID] [int] IDENTITY(1,1) NOT NULL,
	[userID] [int] NOT NULL,
	[RosterName] [nvarchar](20) NOT NULL,
	[SalaryCap] [int] NOT NULL,
	[PlayerTeam] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_SavedRosters] PRIMARY KEY CLUSTERED 
(
	[rosterID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 4/9/2020 9:49:32 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [nvarchar](25) NOT NULL,
	[UserPassword] [nvarchar](25) NOT NULL,
	[Age] [int] NOT NULL,
	[Email] [nvarchar](40) NOT NULL,
	[FirstName] [nvarchar](20) NOT NULL,
	[LastName] [nvarchar](20) NOT NULL,
	[MiddleName] [nvarchar](20) NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NewRoster]  WITH CHECK ADD  CONSTRAINT [FK_NewRoster_SavedRosters] FOREIGN KEY([RosterID])
REFERENCES [dbo].[SavedRosters] ([rosterID])
GO
ALTER TABLE [dbo].[NewRoster] CHECK CONSTRAINT [FK_NewRoster_SavedRosters]
GO
ALTER TABLE [dbo].[PossibleRosters]  WITH CHECK ADD  CONSTRAINT [FK_PossibleRosters_NewRoster] FOREIGN KEY([PlayerID])
REFERENCES [dbo].[NewRoster] ([PlayerID])
GO
ALTER TABLE [dbo].[PossibleRosters] CHECK CONSTRAINT [FK_PossibleRosters_NewRoster]
GO
ALTER TABLE [dbo].[PossibleRosters]  WITH CHECK ADD  CONSTRAINT [FK_PossibleRosters_SavedRosters] FOREIGN KEY([SavedRosterID])
REFERENCES [dbo].[SavedRosters] ([rosterID])
GO
ALTER TABLE [dbo].[PossibleRosters] CHECK CONSTRAINT [FK_PossibleRosters_SavedRosters]
GO
ALTER TABLE [dbo].[SavedRosters]  WITH CHECK ADD  CONSTRAINT [FK_SavedRosters_User] FOREIGN KEY([userID])
REFERENCES [dbo].[User] ([UserID])
GO
ALTER TABLE [dbo].[SavedRosters] CHECK CONSTRAINT [FK_SavedRosters_User]
GO
USE [master]
GO
ALTER DATABASE [FantasyFootballDB] SET  READ_WRITE 
GO
